### PR TITLE
Add missing return

### PR DESCRIPTION
**Pull request by jesenko**
Fixes missing return in PR #8

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by rondale-sc** [comment]
Thanks @jesenko!

**Comment by rondale-sc** [comment]
@rwjblue Need another version bump I suppose?

**Comment by rwjblue** [comment]
@rondale-sc - Yessir.

**Comment by rondale-sc** [comment]
Commin' atcha

**Comment by rwjblue** [comment]
We should also rig up a test harness for these things...

**Comment by rondale-sc** [comment]
Yeah, Pavel and I have talked about this.

**Pull request merged**
